export const REQ_ADD_LOCATION = 'REQ_ADD_LOCATION'; 
export const RCV_ADD_LOCATION_OK = 'RCV_ADD_LOCATION_OK'; 
export const RCV_ADD_LOCATION_NOK = 'RCV_ADD_LOCATION_NOK';  

export const REQ_REMOVE_LOCATION = 'REQ_REMOVE_LOCATION';
export const RCV_REMOVE_LOCATION_OK = 'RCV_REMOVE_LOCATION_OK'; 

export const REQ_REMOVE_ALL_LOCATIONS = 'REQ_REMOVE_ALL_LOCATIONS';
export const RCV_REMOVE_ALL_LOCATIONS_OK = 'RCV_REMOVE_ALL_LOCATIONS_OK'; 

export const REQ_GRANT_LOCATION = 'REQ_GRANT_LOCATION'; 
export const RCV_GRANT_LOCATION_OK = 'RCV_GRANT_LOCATION_OK'; 
export const RCV_GRANT_LOCATION_NOK = 'RCV_GRANT_LOCATION_NOK';  



